### ISSUE TITLE
Create Backend

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#1]
We need to add a node/express/typescript backend inside the `packages` directory. 

Just make sure some basic API boilerplate is in place. Probably could copy the [eth-tech-tree-backend] and put it here.

The purpose of the backend will be to run recurring jobs that refresh the data from Open Source Observer and store it based on timeframes. This way when a user queries a certain time frame we won't have to recalculate everything from scratch.

Since we will have a backend we will make use of aggressive caching so that every request is as fast as possible.

**Comment by swellander** [comment]
Nice, I can get started on this today

**Comment by escottalexander** [comment]
@swellander Thanks! Use the version of eth-tech-tree-backend in this PR: https://github.com/BuidlGuidl/eth-tech-tree-backend/pull/13

It has moved the project to be more of a monorepo structure and you should be able to mostly just copy the `packages/server` and you can delete any ETT specific files.

**Comment by swellander** [comment]
> @swellander Thanks! Use the version of eth-tech-tree-backend in this PR: [BuidlGuidl/eth-tech-tree-backend#13](https://github.com/BuidlGuidl/eth-tech-tree-backend/pull/13)
> 
> It has moved the project to be more of a monorepo structure and you should be able to mostly just copy the `packages/server` and you can delete any ETT specific files.

Great, will do. Thanks @escottalexander !

**Comment by escottalexander** [comment]
Per our conversation on Telegram we don't have a need of this any more. Thanks for your input @swellander!
