### ISSUE TITLE
Remove `weight` field from Metric model

### ISSUE THREAD

**Issue by swellander** [BuidlGuidl/onchain-impact-dashboard#100]
Our Metric model currently looks like this:
```js
export interface IMetric {
  label?: string;
  name: keyof Metrics;
  description: string;
  weight: number;
  activated: boolean;
  order: number;
}
```
We didn't end up using the `weight` field, opting to store that data as a constant in our source code. We can now remove that field from our model.

**Comment by swellander** [comment]
@escottalexander did you have plans for the `order` field?

**Comment by escottalexander** [comment]
The order field is currently being used to guarantee that Impact Index shows first on the front end. It was introduced by Fran here: https://github.com/BuidlGuidl/onchain-impact-dashboard/pull/79

I am fine with removing the `weight` field though.
