### ISSUE TITLE
Show Metric Description in both views

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#103]
Thanks to @swellander's efforts we have descriptions added to the metrics in the database. Now we just need to show those metric descriptions instead of the lorem ipsum.

**Comment by Franpastoragusti** [comment]
@escottalexander I don't see the descriptions in the seed. where are they?

**Comment by swellander** [comment]
@Franpastoragusti they should be in `seed.sample.json` [here](https://github.com/BuidlGuidl/onchain-impact-dashboard/blob/741fafd32c851eb117306b36a6903a526a3ca97a/packages/nextjs/services/mongodb/seed.sample.json#L21851)

**Comment by swellander** [comment]
We'll also need a description for `impact_index`
