### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#15]
![layout](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/22101475/a9348119-3f50-45eb-a1b5-5b6d2b6899c3)

Create a nav bar component. https://www.figma.com/design/SuY5W6zRajPNOrmeCSTvAq/Onchain-Impact-Dashboard?node-id=1-49537&t=A6kTe3hIhRieL0JU-0

Import it inside this file `packages/nextjs/app/layout.tsx`.

The Nav Bar will have
- OP Retro Funding logo
- dark/light mode button
- button/link to [RetroFunding.optimism.io](http://retrofunding.optimism.io/)

**Comment by KcPele** [comment]
working on this

**Comment by Franpastoragusti** [comment]
have on mind the colors for the dark mode
here you can check them
https://app.optimism.io/retropgf

**Comment by KcPele** [comment]
> have on mind the colors for the dark mode here you can check them https://app.optimism.io/retropgf

noted
