### ISSUE TITLE
Leaderboard Layout

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#16]
Without too much concern for the functionality of the components go ahead and stub out the layout as best you can.

Create a component that someone can fill in with the leaderboard list and duplicate `packages/nextjs/components/impact-vector/ImpactVectorGraph.tsx` to a new location and import that component as a stand in for the graph.

https://www.figma.com/design/SuY5W6zRajPNOrmeCSTvAq/Onchain-Impact-Dashboard?node-id=28-36453&t=A6kTe3hIhRieL0JU-4

**Comment by blahkheart** [comment]
I'll work on this

**Comment by Franpastoragusti** [comment]
@blahkheart what is the status of this? I can take care if you don't have time

**Comment by blahkheart** [comment]
@Franpastoragusti I'm actually rounding up with it.. I've just been facing a weird blocker but I'm actively working on it
