### ISSUE TITLE
Integrate with Agora API

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#2]
We will need to query Agora to get project metadata. Here is their API Spec: https://vote.optimism.io/api_v1 
Looks like it is serving mocked data currently but that should change in the next couple of weeks. The only endpoint I have knowledge of needing would be the `projects` endpoint.

We should add this to our ~~backend~~ NextJS app.

**Comment by swellander** [comment]
I can start setting this up
