### ISSUE TITLE
Add caching middleware to backend

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#3]
In our backend API we should create caching middleware that receives a parameter designating the length of time in milliseconds that the call should be cached. If the call does not succeed in finding a cached item, it retrieves the item and the new item is cached for the parameters designated time.

**Comment by KcPele** [comment]
Can we make use of Redis here, it will be added to the backed API which will help in catching and increasing speed and reduce the number of times we hit the database

**Comment by escottalexander** [comment]
> Can we make use of Redis here, it will be added to the backed API which will help in catching and increasing speed and reduce the number of times we hit the database

This might be a nice improvement to make but we may be over engineering to use it from the start.

**Comment by escottalexander** [comment]
Per our conversation on Telegram we don't have a need of this any more.
