### ISSUE TITLE
API Definition [projects GET] 

### ISSUE THREAD

**Issue by Franpastoragusti** [BuidlGuidl/onchain-impact-dashboard#37]
Return a list of ProjectDtos

- [ ] Create ProjectDto entity to match the data used on the leaderboard in each project
- [ ] Fetch Projects from Db
- [ ] Transform to Dtos and return them
- [ ] Update Project Service
- [ ] Move the endpoint to the project folder under /api

**Comment by escottalexander** [comment]
The Agora projects API returns ALL projects from past RPGF rounds. No need to store any that are not included in the `api/stub/mappings` endpoint. The ones in the mapping are the ones that have OSO data that matches the metrics we are displaying.

**Comment by swellander** [comment]
Closed by #46
