### ISSUE TITLE
Create Design Wireframes for primary views

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#4]
We need to design the following views and components: 
- __Leaderboard View__
    1. Shows ranked projects with each project's profile picture, name and rank.
    2. This will likely be over a few hundred projects so a search bar might be nice for scrolling to a projects position (instead of eliminating all other results maybe we should just scroll to project location). 
    3. Chart showing impact of all projects, single overall metric
    4. Selecting a project takes you to the individual project view
    5. Social media sharing buttons
- __Individual Project View__
    1. Project Details
    2. Chart showing individual metrics for the project (15 or so metrics, might be good to enable switching them on and off)
    3. Social Media sharing buttons
- __Social Media Sharing Dialog__
    1. It should be clear to the user that they are sharing (or have the option to share) the specific view they have. For instance, maybe I want to share that my project made it into the top 100. I want the link to show my project at rank 100 instead of the link showing the top ten projects that I don't care about. Perhaps they should be given a choice to "share current view" or "share generic view". 🤔
- __Top Menu__
    1. Should have name of site
    2. Should have button that links to Optimism's sign up form (external)

Feel free to add and adjust if better ideas come to mind.

Jonas said we are free to re-use any components [here](https://www.figma.com/design/eVb3MoRIALsWo6AmcgfOiL/Retro-Funding-Round-4%3A-Sign-Up-%26-Application--(Public-Draft)?node-id=0-1&t=Be4LjY2TtxRvsiio-0).

![image](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/22101475/4093f0fe-2b2c-488e-ae8a-45f926dfc05f)
One thing Jonas mentioned specifically about the design is that they are trying to use this thick margin design with the app inside the margins. That was the only design preference he stated so let's be sure to keep with that feel.

**Comment by KcPele** [comment]
we can have several issues that handle just building out components, and making reference to them in the design,

**Comment by escottalexander** [comment]
The designs are here:
https://www.figma.com/design/SuY5W6zRajPNOrmeCSTvAq/Onchain-Impact-Dashboard?node-id=1-49537&t=xLk9WTWzk3QvzURF-0

Closing this issue as complete though we will make more tweaks in the future.
