### ISSUE TITLE
Add back button when on project view

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#40]
When you click to view more on a project you go to the project details and there is no way to go back to the main view. 
![image](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/22101475/6ebe215e-d9dc-41bc-80b1-38059e797abe)

We need Elena's advice on how to display before we execute.

**Comment by KcPele** [comment]
will be working on this

**Comment by KcPele** [comment]
![Screenshot from 2024-07-12 15-34-31](https://github.com/user-attachments/assets/70af6ac0-e86e-4fd9-8ce2-deee65af2c31)
![Screenshot from 2024-07-12 15-34-55](https://github.com/user-attachments/assets/9081838d-6e00-4652-bd4b-62e8ca2b09e9)
![Screenshot from 2024-07-12 15-35-13](https://github.com/user-attachments/assets/463a23ad-f61c-4b65-a9a9-2e884b6c5056)
![Screenshot from 2024-07-12 15-35-24](https://github.com/user-attachments/assets/ce4b9972-a696-4214-a320-4b84969d4547)
