### ISSUE TITLE
Create new design for main leaderboard view

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#44]
We want this design to closely resemble Jonas' scratch design here:
![RevisedJonasScratch](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/22101475/75d4138d-9b31-4434-b75e-5a0856fb05c3)

Notice we want some BuidlGuidl attribution added to the top header. The location can be changed but we just want to make sure people know they are viewing a dashboard built by the BuidlGuidl.

Let's discuss if there are any ideas about a better way to represent the data. Feel free to bring it up.

**Comment by Franpastoragusti** [comment]
![Leaderboard](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/15233854/1e26bb5b-d6bc-409a-9f9b-caacaff04781)
