### ISSUE TITLE
Redesign project details view

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#45]
It should closely resemble Jonas' scratch design here:
![RevisedJonasScratchProject](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/22101475/345a59be-9861-443d-aa91-71df8c5edcaa)

Let's discuss if there are any ideas about a better way to represent the data. Feel free to bring it up.

**Comment by Franpastoragusti** [comment]
![Individual -project-view](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/15233854/ddac0cfc-43d2-48a6-a643-2d7eed9e26fd)
