### ISSUE TITLE
Fix themes

### ISSUE THREAD

**Issue by Franpastoragusti** [BuidlGuidl/onchain-impact-dashboard#52]
![Leaderboard-1](https://github.com/BuidlGuidl/onchain-impact-dashboard/assets/15233854/cdbca4c5-6079-4ce8-8e74-75dc2fb664c8)

This is what I have seen
- Remove linear gradient on background for dark mode
- Set as default white theme
- Align colors on dark mode
Have on mind that the picture is from the current design but is in process to be changed,If you see more stuff let us know in your pr but please TOUCH ONLY theme related topics
Figma
https://www.figma.com/design/SuY5W6zRajPNOrmeCSTvAq/Onchain-Impact-Dashboard?node-id=317-699&t=voOzApw6N6kK77gg-0

**Comment by escottalexander** [comment]
@Franpastoragusti Can we close this now?
