### ISSUE TITLE
Add ui file structure for two main views, remove old files

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#7]
We are currently awaiting final designs but in the meanwhile we can create a couple of top high level files that will be the:
- overall leaderboard view (this will be the first page users land on
- individual project view

While you are figuring out the best place to put these files, feel free to remove any old files that were related to specific impact-calculator functionality. That would be anything related to the weight adjustments or any other user actions that affected the graph.

**Comment by swellander** [comment]
I can take this one
