### ISSUE TITLE
Show nice placeholder when no data is found for graph

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/onchain-impact-dashboard#74]
Currently several projects have no gas fee data. This will likely be true for the actual data as well. Instead of showing an empty graph that acts like a full graph, lets show "no data" or similar to make it clear that there is no data for that metric.
![image](https://github.com/user-attachments/assets/8c3b47a1-27cf-4974-84a9-c6eec3648675)

**Comment by portdeveloper** [comment]
May I take this?
